### ISSUE TITLE
setState() called after dispose():

### ISSUE THREAD

**Issue by altafShaikh1717** [CHB61/multi_select_flutter#144]
In my code I have dropdownButtonFormField and MultiSelectDialogField

1 If I press submit and validate , it will throw filed required error which is fine 
2 select value in dropdownButtonFormField 
**3. While selecting value from MultiSelectDialogField it throws[setState() called after dispose():]**

Stack over flow link : https://stackoverflow.com/questions/74248509/flutter-multi-select-throws-setstate-called-after-dispose

**Comment by altafShaikh1717** [comment]
Logs 

════════ Exception caught by gesture ═══════════════════════════════════════════
The following assertion was thrown while handling a gesture:
setState() called after dispose(): FormFieldState<List<DdlValues>>#4c0a3(lifecycle state: defunct, not mounted)

This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.

The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().

When the exception was thrown, this was the stack
#0      State.setState.<anonymous closure>
package:flutter/…/widgets/framework.dart:1078
#1      State.setState
package:flutter/…/widgets/framework.dart:1113
#2      FormFieldState.didChange
package:flutter/…/widgets/form.dart:409
#3      __MultiSelectDialogFieldViewState._showDialog.<anonymous closure>.<anonymous closure>
package:multi_select_flutter/dialog/multi_select_dialog_field.dart:388
#4      MultiSelectActions.onConfirmTap
package:multi_select_flutter/util/multi_select_actions.dart:27
#5      _MultiSelectDialogState.build.<anonymous closure>
package:multi_select_flutter/dialog/mult_select_dialog.dart:326
#6      _InkResponseState.handleTap
package:flutter/…/material/ink_well.dart:1072
#7      GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:253
#8      TapGestureRecognizer.handleTapUp
package:flutter/…/gestures/tap.dart:627
#9      BaseTapGestureRecognizer._checkUp
package:flutter/…/gestures/tap.dart:306
#10     BaseTapGestureRecognizer.handlePrimaryPointer
package:flutter/…/gestures/tap.dart:239
#11     PrimaryPointerGestureRecognizer.handleEvent
package:flutter/…/gestures/recognizer.dart:615
#12     PointerRouter._dispatch
package:flutter/…/gestures/pointer_router.dart:98
#13     PointerRouter._dispatchEventToRoutes.<anonymous closure>
package:flutter/…/gestures/pointer_router.dart:143
#14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:617:13)
#15     PointerRouter._dispatchEventToRoutes
package:flutter/…/gestures/pointer_router.dart:141
#16     PointerRouter.route
package:flutter/…/gestures/pointer_router.dart:127
#17     GestureBinding.handleEvent
package:flutter/…/gestures/binding.dart:460

**Comment by altafShaikh1717** [comment]
#18     GestureBinding.dispatchEvent
package:flutter/…/gestures/binding.dart:440
#19     RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart:337
#20     GestureBinding._handlePointerEventImmediately
package:flutter/…/gestures/binding.dart:395
#21     GestureBinding.handlePointerEvent
package:flutter/…/gestures/binding.dart:357
#22     GestureBinding._flushPointerEventQueue
package:flutter/…/gestures/binding.dart:314
#23     GestureBinding._handlePointerDataPacket
package:flutter/…/gestures/binding.dart:295
#24     _invoke1 (dart:ui/hooks.dart:167:13)
#25     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:341:7)
#26     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
Handler: "onTap"
Recognizer: TapGestureRecognizer#9e5af
    debugOwner: GestureDetector
    state: possible
    won arena
    finalPosition: Offset(321.1, 645.1)
    finalLocalPosition: Offset(37.2, 11.7)
    button: 1
    sent tap down

**Comment by altafShaikh1717** [comment]
Posted my answer at [stacjk overflow](https://stackoverflow.com/questions/74248509/flutter-multi-select-throws-setstate-called-after-dispose)

Earlier in My code, If I validate then following save was called

`Future<void> _saveForm() async {
   final isValid = _form.currentState.validate();
   FocusScope.of(context).unfocus(); // This line was causing issue
   bool isSuccess = true;
   if (!isValid) {
     return;
   }
   // save code

}`
If Validate form and select Dropdown value and then Multi select value was throwing setState() called after dispose():

I changed code as below and now its working

`Future<void> _saveForm() async {
    final isValid = _form.currentState.validate();
   
    bool isSuccess = true;
    if (!isValid) {
      return;
    }
    FocusScope.of(context).unfocus(); // move this line to after if condition
    // save code

}`
