### ISSUE TITLE
Error running example

### ISSUE THREAD

**Issue by bartonhammond** [CHB61/multi_select_flutter#8]
![Screen Shot 2020-11-17 at 10 32 55 AM](https://user-images.githubusercontent.com/1282364/99418119-49af7700-28c0-11eb-92ba-b9a5ec925c14.png)
```
[example](master)$ flutter run
Running "flutter pub get" in example...                             1.4s
Launching lib/main.dart on iPhone SE (2nd generation) in debug mode...
 
Project base configurations detected, removing.
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        17.9s
Xcode build done.                                           38.1s
Waiting for iPhone SE (2nd generation) to report its views...          4ms
Syncing files to device iPhone SE (2nd generation)...              201ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on iPhone SE (2nd generation) is available at:
http://127.0.0.1:51755/fhT3xglX-Nw=/
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following _TypeError was thrown building
flutter: MultiSelectBottomSheetField<Animal>-[LabeledGlobalKey<FormFieldState<dynamic>>#ad7f7](dirty, state:
flutter: FormFieldState<List<Animal>>#49d18):
flutter: type '(List<Animal>) => Null' is not a subtype of type '(List<dynamic>) => void'
flutter:
flutter: The relevant error-causing widget was:
flutter:   MultiSelectBottomSheetField<Animal>-[LabeledGlobalKey<FormFieldState<dynamic>>#ad7f7]
flutter:   file:///Users/bartonhammond/flutter/multi_select_flutter/example/lib/main.dart:170:15
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      new _MultiSelectBottomSheetFieldView._withState (package:multi_select_flutter/bottom_sheet/multi_select_bottom_sheet_field.dart:257:27)
flutter: #1      new MultiSelectBottomSheetField.<anonymous closure> (package:multi_select_flutter/bottom_sheet/multi_select_bottom_sheet_field.dart:177:22)
flutter: #2      FormFieldState.build (package:flutter/src/widgets/form.dart:528:26)
flutter: #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4744:28)
flutter: #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627:15)
flutter: #5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
flutter: #6      Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
flutter: #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
flutter: #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4791:11)
flutter: #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
flutter: #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
flutter: #11     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6236:32)
flutter: ...     Normal element mounting (98 frames)
flutter: #109    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
flutter: #110    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6236:32)
flutter: ...     Normal element mounting (102 frames)
flutter: #212    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
flutter: #213    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6236:32)
flutter: ...     Normal element mounting (136 frames)
flutter: #349    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
flutter: #350    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6236:32)
flutter: ...     Normal element mounting (273 frames)
flutter: #623    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
flutter: #624    Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
flutter: #625    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1252:16)
flutter: #626    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1223:5)
flutter: #627    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1165:17)
flutter: #628    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2683:19)
flutter: #629    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1164:13)
flutter: #630    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:974:7)
flutter: #631    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:955:7)
flutter: (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
flutter:
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by CHB61** [comment]
Hi @bartonhammond,

Thanks for pointing this out. The example app is using verson 3.0.1 of the package but the bug has since been fixed. I'll be sure to update the version in the example :)
