### ISSUE TITLE
example error

### ISSUE THREAD

**Issue by kadirkos** [CHB61/multi_select_flutter#80]
════════ Exception caught by gesture ═══════════════════════════════════════════
The following _TypeError was thrown while handling a gesture:
type 'List<Animal?>' is not a subtype of type 'List<Animal>?' of 'value'

When the exception was thrown, this was the stack
#0      FormFieldState.didChange (package:flutter/src/widgets/form.dart)
#1      __MultiSelectDialogFieldViewState._showDialog.<anonymous closure>.<anonymous closure>
#2      MultiSelectActions.onConfirmTap
#3      _MultiSelectDialogState.build.<anonymous closure>
#4      _InkResponseState._handleTap
#5      GestureRecognizer.invokeCallback
#6      TapGestureRecognizer.handleTapUp
#7      BaseTapGestureRecognizer._checkUp
#8      BaseTapGestureRecognizer.handlePrimaryPointer
#9      PrimaryPointerGestureRecognizer.handleEvent
#10     PointerRouter._dispatch
#11     PointerRouter._dispatchEventToRoutes.<anonymous closure>
#12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#13     PointerRouter._dispatchEventToRoutes
#14     PointerRouter.route
#15     GestureBinding.handleEvent
#16     GestureBinding.dispatchEvent
#17     RendererBinding.dispatchEvent
#18     GestureBinding._handlePointerEventImmediately
#19     GestureBinding.handlePointerEvent
#20     GestureBinding._flushPointerEventQueue
#21     GestureBinding._handlePointerDataPacket
#25     _invoke1 (dart:ui/hooks.dart:169:10)
#26     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#27     _dispatchPointerDataPacket (dart:ui/hooks.dart:88:31)
(elided 3 frames from dart:async)
Handler: "onTap"
Recognizer: TapGestureRecognizer#d01fa
    debugOwner: GestureDetector
    state: possible
    won arena
    finalPosition: Offset(317.3, 638.4)
    finalLocalPosition: Offset(35.5, 29.0)
    button: 1
    sent tap down
════════════════════════════════════════════════════════════════════════════════

**Comment by anglesen1120** [comment]
final _items = _animals
      .map((animal) => MultiSelectItem<Animal?>(animal, animal.name))
      .toList(); will be fix your issue

**Comment by GabrielLana** [comment]
I'm having the same issue, already tried this approach, but still getting the sama error:
![Screenshot_1](https://user-images.githubusercontent.com/81386246/148453326-d4ca6964-add2-43cf-8756-55924bec3aca.png)
![Screenshot_2](https://user-images.githubusercontent.com/81386246/148453334-8cf9549e-823c-4659-8cad-a8208ffd4971.png)

**Comment by GabrielLana** [comment]
Well now I solved my problem, I just did a cast to "values", and now its working.
![image](https://user-images.githubusercontent.com/81386246/148596448-aea371d4-77c8-4a40-9089-91ec9406fc76.png)

**Comment by shinriyo** [comment]
```
final _items = _animals
    .map((animal) => MultiSelectItem<Animal?>(animal, animal.name))
    .toList();
```
